# Generated by Django 5.1.4 on 2025-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsuleapp', '0002_timecapsule_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsule',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
